# Basic Python

## 1. Split this string

In [10]:
s = "Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [11]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
mylist = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
s=mylist[3][1][2];
print(s)

['hello']


In [13]:
me = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(me['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [15]:
import numpy as np
sample=np.zeros(10)
print("An array of 10 zeros:")
print(sample)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
import numpy as np
sample1=np.ones(10)*5
print("An array of 10 fives:")
print(sample1)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [17]:
import numpy as np
sample2=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(sample2)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
import numpy as np
sample3 =  np.arange(0, 9).reshape(3,3)
print(sample3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
  
sample4 = np.concatenate((arr1, arr2), axis = None)
  
print (sample4)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd
data = [['RIYA', 10], ['AIRA', 15], ['DAFI', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0  RIYA   10
1  AIRA   15
2  DAFI   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [29]:
import pandas as pd
dRan1 = pd.date_range(start ='1-1-2023', periods = 41)
  
print(dRan1)


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [30]:
dict = {'name':['aaa', 'bbb', 'ccc'],
        'score':[22,25,24]}
 
df = pd.DataFrame(dict,index=['1','2','3'])
 
df

name  score
1  aaa     22
2  bbb     25
3  ccc     24